### ISSUE TITLE
Implement loading / splash screen

### ISSUE THREAD

**Issue by danwalmsley** [VitalElement/AvalonStudio#109]
I'd imagine implement as a popup that is displayed as soon as the application is run.

nice image, with status label, can show loading process.

Also show git build number and version number.

**Comment by Seeker1437** [comment]
I will ha be a PR for this shortly

**Comment by danwalmsley** [comment]
Woohoo 🙂

**Comment by Seeker1437** [comment]
I am very sorry for making this take so long!
