### ISSUE TITLE
Add Makefile toolchain

### ISSUE THREAD

**Issue by danwalmsley** [VitalElement/AvalonStudio#121]
Really simple toolchain implementation, with settings dialogs to add commands, i.e. 
make clean,
make x
make 
and also make xxx  -j8

**Comment by danwalmsley** [comment]
Current toolchains should be able to Import and Export their standard libraries via IStandardLibrary mechanism.

GCC Compilers should be able to export the paths to their binaries via IGCCToolchain interface.

These can then be used by by makefile toolchains like BitThunder.

**Comment by jameswalmsley** [comment]
I would say we could export a special environment variable which includes the path an optional make include file.

    -include vebuild.mk

The - infront of include makes Make ignore if it cannot be found.

This could then include some automatically defined paths based on the environment variables set before the build process is started.

E.g. VEBUILD_TOOLCHAIN=/opt/vebuild/arm-linux-gcc/v1.0/bin/arm-linux-

Etc etc.

It could also try to extract CFLAGS in-order to detect include paths etc.

Also it would be beneficial to select the kind of environment to be used.
E.g. bash (default), or native for (windows/bash depending on platform).

**Comment by danwalmsley** [comment]
Sounds good, although not VEBUILD we changed the command line build system to Avalon!

Also not sure about the environment, as there is none, we simply run the executables, i.e. gcc or make and intercept their stdout and stdin... so is there an environment there?

**Comment by jameswalmsley** [comment]
There is an environment.. Like the PATH and other env variables that you set when you fork the make process.

E.g. the bitthunder test we did has a bash system in its environment.
