### ISSUE TITLE
Load Projects Asynchronously and Reload if they are modified Externally

### ISSUE THREAD

**Issue by danwalmsley** [VitalElement/AvalonStudio#145]
- [ ]  Reload projects if the project file is modified externally.
- [ ]  Asynchronously Load solutions in the solution explorer with Progress bar, so UI is not frozen in large projects, i.e. BitThunder project.
- [ ] Context menus need to distinguish between Deleting a file and Exclude from Project (currently remove)

**Comment by danwalmsley** [comment]
Extend the LoadFiles to used the internal AddFile (string path and string folder) methods, which will invoke onto ui thread where it exists.

Also Solutions should display projects in a loading state before they are loaded.

**Comment by Seeker1437** [comment]
>Also Solutions should display projects in a loading state before they are loaded.

I propose a limit on how projects load at once. Also, Visual Studio secretly has a smart loading model the will prioritize loading projects that are required to get the startup project to be usable and then it will reprioritze if to try at open a different project.

**Comment by Seeker1437** [comment]
That or Iight be crazy hehe
