### ISSUE TITLE
Closing application while running

### ISSUE THREAD

**Issue by mathias234** [VitalElement/AvalonStudio#163]
If you close a console applcation while the debugging is running the editor will crash. tested multiple times.

**Comment by 0xFireball** [comment]
Can confirm that this occurs.

**Comment by danwalmsley** [comment]
Thanks guys will take a look

**Comment by danwalmsley** [comment]
I'm going to have a major overhaul of the debugging engine, so will make sure this gets sorted

**Comment by danwalmsley** [comment]
Debugging engine now completely replaced, this no longer happens.
