### ISSUE TITLE
Implement Run to Line

### ISSUE THREAD

**Issue by danwalmsley** [VitalElement/AvalonStudio#261]
see visual studio feature here...
https://www.visualstudio.com/en-us/news/releasenotes/vs2017-relnotes#willow

**Comment by 0xFireball** [comment]
would this be similar in implementation to breakpoints?

**Comment by danwalmsley** [comment]
its a new visual studio feature, looks to me like when your in the editor, a common scenario everyone does, is set a breakpoint, then click debug, so it stops at a specific place..

new visual studio, if you hover next to breakpoint margin a green play button appears and the program instantly starts and stops at that line, without you having to set a breakpoint and remove it.

**Comment by danwalmsley** [comment]
having lots of these tiny features, they all add up to a quality experience.
