### ISSUE TITLE
Remove Redundant LibGit2Sharp Nuget Packages

### ISSUE THREAD

**Issue by ImaBrokeDude** [VitalElement/AvalonStudio#38]
LibGit2Shapr and LibGit2Sharp.NativeBinaries have very little different between them right?

**Comment by danwalmsley** [comment]
Both packages are needed, eventually only in AvalonStudio.Models.

One provides libgitsharp, the other libgit2 binaries for windows, mac and linux.

**Comment by ImaBrokeDude** [comment]
Ah LibGit2Sharp does provide native binaries but probably not compatible with lonux, i see

**Comment by danwalmsley** [comment]
I think it didn't before... but now when you add the libgit2sharp... it adds the native binaries and you get all of them... I will close the issue.
