### ISSUE TITLE
Windows binaries doesn't work

### ISSUE THREAD

**Issue by tezine** [VitalElement/AvalonStudio#387]
Hi, AvalonStudio seems promising, but its binaries are not working under Windows 10. 
The IDE opens fine, but whenever I attempt to create a new C# solution, the IDE crashes. 
If I attempt to create a typescript project, nothing happens after set the project's name and pressing "ok" . 
When I open a dotnet core project, code complete doesn't work and doesn't compile or run. 
Any ideas?

**Comment by danwalmsley** [comment]
@tezine hey, welcome, a lot of these things are being actively developed. Its not yet posible to create a new dotnet project from avalon studio, however recent builds can now open, compile and debug.

Are you running Windows, Linux or Mac?

**Comment by tezine** [comment]
That's good news! I hope you have enough time to work on it. 
I'm interested in a Multi-Platform wpf development using dotnet core and c#.

**Comment by danwalmsley** [comment]
@tezine I hope you know about https://github.com/avaloniaUI/Avalonia

We hope to integrate a full development solution to support it soon, but we need contributors to help make it a reality. We will get there sooner or later though.
