### ISSUE TITLE
Windows download link is broken

### ISSUE THREAD

**Issue by bubnenkoff** [VitalElement/AvalonStudio#415]
subj

**Comment by danwalmsley** [comment]
@bubnenkoff ok taking a look into this, hopefully should be restored shortly, for now you can download here: https://ci.appveyor.com/project/danwalmsley/avalonstudio/build/0.2.0.3025/artifacts

**Comment by danwalmsley** [comment]
If you are interested in trying to use AvalonStudio for D, this work is currently on a separate branch and hasn't made it to master yet.

Overall the project is not quite ready for daily use, but we welcome you to come and test and give feedback or get involved :)

**Comment by bubnenkoff** [comment]
I am used that nothing works..))
Yes, I need D. I am too tied to write code in Sublime.

**Comment by danwalmsley** [comment]
@bubnenkoff well I hope with your help we can make the best D IDE that is out there :)

**Comment by danwalmsley** [comment]
link is fixed.
