### ISSUE TITLE
Implenent indentation strategy

### ISSUE THREAD

**Issue by danwalmsley** [VitalElement/AvalonStudio#54]
Perhaps language service provides the indentation strategy?

**Comment by Seeker1437** [comment]
This is editor level to me

**Comment by Seeker1437** [comment]
Then the language service can override those editor settings

**Comment by danwalmsley** [comment]
Its language specific, the way you indent  callis different to c++ and csharp,  the language service will  listento events from editor to decide when to do the indentation, so you are right it is editor level, its just using the language service to say hey  howdo I do the indentation.

**Comment by danwalmsley** [comment]
Implemented
