### ISSUE TITLE
System.AggregateException

### ISSUE THREAD

**Issue by se5a** [VitalElement/AvalonStudio#545]
https://gist.github.com/se5a/4ec9a353b3349e45b094421f3c36393e

This happens when attempting to debug AS from inside a copy of AS. 
This is supposed to be fixed by replacing the corapi.portable.dll 
however after replacing the dll, AS nolonger successfully loads all the projects in the sln. 
it hangs, not unresponsive, just stops loading.

**Comment by danwalmsley** [comment]
(Linux)

**Comment by danwalmsley** [comment]
This is now fixed on `implement-roslyn-workspaces` branch.
