### ISSUE TITLE
Bundle MacOS release as an .app

### ISSUE THREAD

**Issue by phil-harmoniq** [VitalElement/AvalonStudio#552]
I was a bit confused about how to launch AvalonStudio after download the release. MacOS applications are typically bundled in an `.app` folder. Is this something you are currently looking into? If I find some time, I may be able to dig through the project and submit a PR. Thanks for working on this, we need more cross-platform C# IDEs. :)

**Comment by danwalmsley** [comment]
@phil-harmoniq thanks for the great feedback! :) yeah we definitely need this, is it possible to generate a .app package on a Linux or windows build server? or will we need mac os to do that?

**Comment by phil-harmoniq** [comment]
I believe you will need a MacOS build environment, but I'll have to double-check. I noticed that you're using Travis CI and I know that they have an option for Mac builds. If you don't have a Mac to try it out on, I might be able to whip something up when I find the time and submit a PR.

**Comment by danwalmsley** [comment]
Yes that would be awesome, hopefully some script we can call at the end of existing build script that generates a macos package.

**Comment by danwalmsley** [comment]
done

**Comment by danwalmsley** [comment]
https://github.com/VitalElement/AvalonStudio/releases
