### ISSUE TITLE
Cannot clone repository, downlad link not functionnal

### ISSUE THREAD

**Issue by Xarkam** [VitalElement/AvalonStudio#555]
Hello,

I try to clone but I have one error:
(`git clone https://github.com/VitalElement/AvalonStudio --recursive`)
```
Error: The server does not allow a request for the unlisted object 116bd34961f9789ab6d96569286438f954edb4ec
Sub-module path 'AvaloniaEdit' recovered, but it did not contain 116bd34961f9789ab6d96569286438f954edb4ec. Direct recovery of this commit failed.
```
I can't build because many missing references

I also tried to download package but whole link return a page like this:
(here is the return for windows package)
```
<Error>
<Code>BlobNotFound</Code>
<Message>
The specified blob does not exist. RequestId:d32fbe1c-001e-0006-41be-ab4d9c000000 Time:2018-02-22T09:21:38.3249287Z
</Message>
</Error>
``` 

Thanks.

**Comment by LiHRaM** [comment]
Hey, I had similar problems. They were solved by running the two following commands:
```
$ git submodule sync
$ git submodule update --init
```

**Comment by danwalmsley** [comment]
@Xarkam the answer @LiHRaM provided will work as long as you checkout `develop` branch first.

**Comment by danwalmsley** [comment]
The download link I will have to fix that!

**Comment by danwalmsley** [comment]
I will also do another minor release shortly that will merge our develop branch to master so the cloning issue will no longer happen.

**Comment by andreevlex** [comment]
Not copy

```bash
fatal: reference is not a tree: 116bd34961f9789ab6d96569286438f954edb4ec
Unable to checkout '116bd34961f9789ab6d96569286438f954edb4ec' in submodule path 'AvaloniaEdit'
```

I tried the command

```bash
$ git submodule sync
$ git submodule update --init
```

It's not working.

**Comment by danwalmsley** [comment]
@andreevlex what branch did you try?

**Comment by danwalmsley** [comment]
ok fix pushed to master!

**Comment by Xarkam** [comment]
Thanks. It works perfectly.
