### ISSUE TITLE
Only pull single branch when installing packages

### ISSUE THREAD

**Issue by danwalmsley** [VitalElement/AvalonStudio#56]
See here:

http://stackoverflow.com/questions/6368987/how-do-i-fetch-only-one-branch-of-a-remote-git-repository

**Comment by Seeker1437** [comment]
I think VS pulls them all too

**Comment by danwalmsley** [comment]
yes, its just a pain if Windows pulls in a Toolchain + the mac variant  + the Linux variant, you end up with 4-500 mb of redundant files. My thinking is that there will be problems getting libgit2sharp to support this.

**Comment by Seeker1437** [comment]
You can pull asingke specific using a CheckoutOptions I believe, its a trick i use for my private server

**Comment by danwalmsley** [comment]
@Seeker1437 cheers mate will look into it.

**Comment by danwalmsley** [comment]
Redundant we now use nuget.
