### ISSUE TITLE
Crash when removing <Grid> element

### ISSUE THREAD

**Issue by Krutonium** [VitalElement/AvalonStudio#612]
Reproduction Steps:

1. Open [this](https://github.com/VitalElement/AvalonStudio/files/1813805/AvaloniaNETCoreApp1.zip) in AS
2. Open `MainWindow.xaml`
3. Remove the opening `<Grid>` element, starting at the `d` and using the backspace key.

AS will crash before removing G.

![screenshot 13](https://user-images.githubusercontent.com/3945538/37441292-18586208-27d7-11e8-83b4-7ad88f54af13.png)

**Comment by danwalmsley** [comment]
This is the regex in the syntax highlighter, it needs to exclude `<>`
