### ISSUE TITLE
Binary links are broken

### ISSUE THREAD

**Issue by nopara73** [VitalElement/AvalonStudio#649]
https://github.com/VitalElement/AvalonStudio#try-the-bleeding-edge-builds

![image](https://user-images.githubusercontent.com/9156103/40007705-b77dba84-57c7-11e8-9b67-b46f9e4afdd2.png)

**Comment by danwalmsley** [comment]
@nopara73 I will get a release done later today and fix the broken links.

**Comment by Shando** [comment]
@danwalmsley  links still not working? Any chance they can be updated soon? 

Thanks in advance.

**Comment by danwalmsley** [comment]
Hey iv not been able to do a release because of some showstopper bugs in Avalonia, they have mostly been sorted now hopefully I can get one ready this weekend or Monday.

**Comment by danwalmsley** [comment]
ok v0.4.5 release published https://github.com/VitalElement/AvalonStudio/releases/tag/v0.4.5

Linux .deb package coming shortly.
