### ISSUE TITLE
Android/iOS stability and scalability?

### ISSUE THREAD

**Issue by angelsix** [VitalElement/AvalonStudio#651]
I have some open source projects I will be making Android/iOS apps on shortly, and I hate Xamarin, used it for many years now and its awful and full of bugs and has been all along.

I do training videos and have quite a following now, and even though I will teach Xamarin as people want those lessons, I know how awful Xamarin is and would like to find a better cross platform solution.

I've in fact been looking at making my own full cross-platform UI for Win/Linux/Mac/iOS as could not find any and then one of the guys who watches my videos pointed me to this project. It looks very promising.

My question is more about the performance and scale-ability of this framework. For example what do you compile down to for Android/iOS and how are you doing the lists, virtualization, rendering etc... Is it something simple like a web browser hosted inside the app or is it compiled to native storyboards/layout files like you would build natively for the platforms? 

Also what support do you have for all the mobile specific features like background modes, notifications, sharing intents, lifecycle events and so on?

**Comment by danwalmsley** [comment]
@angelsix welcome firstly, im going to move this issue to the main Avalonia repo, since your question relates to the AvaloniaUI Framework, (AvalonStudio is an IDE based on Avalonia and targeting Avalonia, C#, C/ C++).
 
I will try to answer your query over there.
