### ISSUE TITLE
[Header] Make Minimize/Maximize/Close More Ergonomic

### ISSUE THREAD

**Issue by nopara73** [VitalElement/AvalonStudio#662]
@danwalmsley As I am designing the GUI I am going to open some issues those will be related to Wasabi Wallet.  

@lontivero @danwalmsley If any of you start working on an issue I opened, please write it, because I don't want you guys to work on the same issues in parallel.  

![image](https://user-images.githubusercontent.com/9156103/40941719-c65b42b8-6886-11e8-9e6b-910d389b2c91.png)

The above icons should have tooltips:

- Minimize
- Maximize/ Restore Down
- Close

At Maximize/ Restore Down not only the tooltip, but also the icon must change depending on the window position.  

See example: Visual Studio.

**Comment by lontivero** [comment]
Maximize/Restore button doesn't change depending on the windows status yet.
