### ISSUE TITLE
[Header] Fix Minimize Icon

### ISSUE THREAD

**Issue by nopara73** [VitalElement/AvalonStudio#663]
![image](https://user-images.githubusercontent.com/9156103/40942317-c9d8efe2-6888-11e8-827e-a4abd861a0e4.png)
The minimize icon is in the upper position. It's traditionally in the bottom:
![image](https://user-images.githubusercontent.com/9156103/40942387-f81a7b8c-6888-11e8-916f-8a2097b29cbe.png)

**Comment by lontivero** [comment]
I take it. I will work on develop branch were @nopara73 find it.
