### ISSUE TITLE
[Popup] Disable Main Window When Popup Opened

### ISSUE THREAD

**Issue by nopara73** [VitalElement/AvalonStudio#669]
Whenever a popup window opens the main window should be unclickable and the popup should stay on top.  

![image](https://user-images.githubusercontent.com/9156103/40948247-3e4bf5fe-68a2-11e8-9323-ccddd4c020c9.png)

**Comment by danwalmsley** [comment]
This requires this PR to be finished.

https://github.com/AvaloniaUI/Avalonia/pull/1542

**Comment by danwalmsley** [comment]
now possible

**Comment by nopara73** [comment]
Finally!
