### ISSUE TITLE
Integrate support for NXP and Cypress

### ISSUE THREAD

**Issue by danwalmsley** [VitalElement/AvalonStudio#69]
http://www.nxp.com/products/microcontrollers-and-processors/arm-processors/kinetis-cortex-m-mcus:KINETIS

http://www.nxp.com/products/microcontrollers-and-processors/arm-processors/kinetis-cortex-m-mcus:KINETIS

**Comment by KammutierSpule** [comment]
Cypress, you mean:
http://www.cypress.com/products/32-bit-arm-cortex-m-psoc

**Comment by danwalmsley** [comment]
@KammutierSpule thanks Mario
