### ISSUE TITLE
Previewer not compatible with netcoreapp2.0

### ISSUE THREAD

**Issue by thezaza101** [VitalElement/AvalonStudio#699]
Issue 
![avalonerror](https://user-images.githubusercontent.com/27200279/44070839-6afce726-9fc9-11e8-8951-3a70e6d364ad.png)

I have the following dotnetcore versions installed:
2.0.5, 2.0.7, and 2.1.2 

2.1.2 has version 4.6.26629.01 of System.Runtime.dll

**Comment by danwalmsley** [comment]
Hey which branch did you try?

**Comment by thezaza101** [comment]
I've cloned the develop (default) branch. Master does not seem to compile due to versioning issues: [compile errors](https://pastebin.com/raw/A2HuNjH9)

**Comment by danwalmsley** [comment]
Did you create the project in avalonstudio?

**Comment by thezaza101** [comment]
Yes, its the "Avalonia .NET Core App" template.

Interestingly enough i get a different error when opening the same project using the pre-compiled version of AvalonStudio.

![avalonerror2](https://user-images.githubusercontent.com/27200279/44240324-e3c77700-a200-11e8-8c18-4565568ead64.png)

**Comment by SuperJMN** [comment]
I'm getting the same error with the latest build.

**Comment by danwalmsley** [comment]
So you have. Net core 2.1 sdk installed?

**Comment by SuperJMN** [comment]
I'm getting this...

![image](https://user-images.githubusercontent.com/3109851/44976916-ddf2c500-af66-11e8-9506-cc53622634c0.png)
... after installing this ".NET Core 2.1 SDK - Windows x64 Installer (v2.1.401)"

**Comment by danwalmsley** [comment]
Ok 2 things:
1) the original error in this post goes away if the project targets netcoreapp2.1, i need to investigate and understand why this happens.


@SuperJMN  your last error:
2) you must target at least avalonia build 0.6.2-build5810-beta

**Comment by danwalmsley** [comment]
ok just pushed fixes for these issues to master.


Please re-open if you still have issues.
