### ISSUE TITLE
Refactor AvalonStudio.Extensibility to make Source Control Managers Pluggable as well

### ISSUE THREAD

**Issue by ghost** [VitalElement/AvalonStudio#70]
SO for example right now Git exists directly in AvalonStudio.Extensibility, however there are toehr SCMs like Bazaar or SVN that could be supported through the MEF flow much like how the debuggers and language services work.

It may increase the availabilityif AvalonStudio in the future and be future proof in terms of the introduction of new SCM technologies.

A user would then only need to update the Assembly Implementing the SCM Export instead of the whole Extensibility framework.

**Comment by danwalmsley** [comment]
Yes this is  definitely needed, I  think git should come first. We will also need to implement a diff and merge tool,  with a common interface all scm can implement. That way they produce  their own controls that go in our equivalent of Team Explorer but the interface is  completely customto git or  bazaar or whatever it is. Git should be the first class citizen here.

This is  somethingthat requires our plugin framework to move forward a tiny bit,  then cam be implemented independently.

I'm wondering if we need to move away from MEF if we want to support .net core  but that can be in future.

**Comment by danwalmsley** [comment]
I believe the work iv done decoupling current controls should be enough to implement a Git source control plugin now.

**Comment by danwalmsley** [comment]
Let me know if your satisfied with the work, I don't know if your interested in implementing a git plugin, that works similarly to the Visual Studio one.

**Comment by Seeker1437** [comment]
I will take a look! :D
