### ISSUE TITLE
Debian build doesn't generate

### ISSUE THREAD

**Issue by bastisawesome** [VitalElement/AvalonStudio#708]
I've run `package-debian.sh` and it gets to the end and outputs:
```
dpkg-deb: building package 'avalon-studio' in '/home/bast/misc/AvalonStudio/packages/deb-build/avalon-studio_0.4.5-444-g3dad3ae.deb'.
```

But in the packages directory there is no .deb for the latest build of AS.

**Comment by danwalmsley** [comment]
The message is wrong it ends up in deb-out dir.
https://github.com/VitalElement/AvalonStudio/blob/develop/packages/package-debian.sh#L27

we had to move the file to work with our CI script, I will fix the message. thanks
