### ISSUE TITLE
Generalize DockTabControl to handle non-document windows

### ISSUE THREAD

**Issue by ghost** [VitalElement/AvalonStudio#71]
I think we should Generalize the tab control a bit more too, because the docking would work for things that aren't docks too.

For example the solution explorer could be a dock tab.

Also making this main tab control extensible would be a very nice thing like you see in the picture below, the tabs can be color coded to a project if more than one exists. 

![Visual Studio with Several no Document Views in the Dock Tab area](http://puu.sh/oslKn/5292827267.png)

**Comment by danwalmsley** [comment]
Yeh my document tabs are slightly specialised at the moment, if  you run avalon studio you will see when you open a file it docks to right hand side. Until user changes something, but would be nice if that was an extension

**Comment by danwalmsley** [comment]
I will convert the DocTab from a UserControl to an actual control soon.

**Comment by Seeker1437** [comment]
Hardcoooore, thank man, just helps me feel a little better adding all kinds of stuff to it.

**Comment by danwalmsley** [comment]
We can now dock anything here... #172
