### ISSUE TITLE
Cannot compile cloned git or v0.62 source

### ISSUE THREAD

**Issue by 2haloes** [VitalElement/AvalonStudio#722]
Hello, 

I've found that on top of issues with cloning this repository (See #721 ), even when I pull all of the parts together, I still can't get the code to compile.

Using the [v0.6.2 tree](https://github.com/VitalElement/AvalonStudio/tree/v0.6.2) to clone all of the missing parts from the linked repositories, I got a strange error when compiling using 'dotnet build' or the 'build.sh' file

`CodeCompletion/PopupWithCustomPosition.cs(13,34): error CS0508: 'PopupWithCustomPosition.GetPosition()': return type must be 'PixelPoint' to match overridden member 'Popup.GetPosition()' [/home/haloes/builds/AvalonStudio/AvaloniaEdit/src/AvaloniaEdit/AvaloniaEdit.csproj]`

This error was generated while using the [AvaloniaEdit linked tree](https://github.com/AvaloniaUI/AvaloniaEdit/tree/cadb5c76ba11f7d685cf36dccfbb51df2c73ebc3) for the 0.6.2 release and for the current git version, the linked tree outright doesn't exist (See linked issue above) so I'm stuck on what to do

**Comment by rakuten** [comment]
i just compile succeed by release/v0.6.2

```shell
git clone -b release/v.0.6.2 https://github.com/VitalElement/AvalonStudio --recursive
cd AvalonStudio/AvalonStudio/AvalonStudio
dotnet restore
dotnet build
cd bin/Debug/netcoreapp2.2
dotnet ./AvalonStudio.dll
```

It is possible that you need to repeat the "dotnet restore" multiple times until the timeout prompt no longer appears.

i use Mac, os version 10.14.4

Hope to be helpful

**Comment by danwalmsley** [comment]
iv finally got around to fixing the develop branch.

@rakuten i'll be doing a new release pretty shortly that will solve your issue.
