### ISSUE TITLE
AvalonStudio Fails to compile (XmlParser.cs(311,31): error CS1525: Invalid expression term '=')

### ISSUE THREAD

**Issue by Morronic** [VitalElement/AvalonStudio#750]
If you get an error compiling using dotnet `XmlParser.cs(311,31): error CS1525: Invalid expression term '='`
Here is how to resolve it:

Open the [ProjectDir]\AvalonStudio\AvalonStudio\Avalonia.Ide\src\Avalonia.Ide.CompletionEngine\XmlParser.cs file and change line 311. 
Instead of: `var clonedStack = = new Stack<int>(new Stack<int>(_containingTagStart));` 

![Avalonia Error 01](https://user-images.githubusercontent.com/17126197/87501887-39477100-c62e-11ea-8517-d133ba64a2ed.png)

Type: `var clonedStack = new Stack<int>(new Stack<int>(_containingTagStart));`

![Avalonia Error Fix 01](https://user-images.githubusercontent.com/17126197/87501903-3ea4bb80-c62e-11ea-886d-08cb14b146a5.png)

Save the file and try to recompile using dotnet build.
Happy Coding!!

**Comment by mvfranz** [comment]
What is the timeline to getting this fix applied?  Currently AvalonStudio cannot be built when checked out and is very frustrating when you are new to the project.

It should be noted that Avalonia.Ide fixed this issue 3 days after it was introduced, so this is actually a submodule reference issue.
