### ISSUE TITLE
Build error on macOS 10.14.6 

### ISSUE THREAD

**Issue by qezz** [VitalElement/AvalonStudio#764]
I'm trying to build the AvalonStudio, but get the following error.
Error fetching `https://dotnet.myget.org/F/dotnet-core/api/v3/index.json` due to certificate issues.

```
$ dotnet restore

...

  Restored /Users/username/sources/AvalonStudio/AvalonStudio/AvalonStudio.Controls.Standard/AvalonStudio.Controls.Standard.csproj (in 118 ms).
/usr/local/share/dotnet/sdk/5.0.103/NuGet.targets(131,5): error : Unable to load the service index for source https://dotnet.myget.org/F/dotnet-core/api/v3/index.json. [/Users/username/sources/AvalonStudio/AvalonStudio/AvalonStudio/AvalonStudio.csproj]
/usr/local/share/dotnet/sdk/5.0.103/NuGet.targets(131,5): error :   The SSL connection could not be established, see inner exception. [/Users/username/sources/AvalonStudio/AvalonStudio/AvalonStudio/AvalonStudio.csproj]
/usr/local/share/dotnet/sdk/5.0.103/NuGet.targets(131,5): error :   The remote certificate is invalid according to the validation procedure: RemoteCertificateNameMismatch [/Users/username/sources/AvalonStudio/AvalonStudio/AvalonStudio/AvalonStudio.csproj]
Microsoft (R) Build Engine version 16.8.3+39993bd9d for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
/usr/local/share/dotnet/sdk/5.0.103/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.EolTargetFrameworks.targets(28,5): warning NETSDK1138: The target framework 'netcoreapp2.2' is out of support and will not receive security updates in the future. Please refer to https://aka.ms/dotnet-core-support for more information about the support policy. [/Users/username/sources/AvalonStudio/AvalonStudio/AvalonStudio.Languages.Xaml/AvalonStudio.Languages.Xaml.csproj]
/usr/local/share/dotnet/sdk/5.0.103/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.EolTargetFrameworks.targets(28,5): warning NETSDK1138: The target framework 'netcoreapp2.0' is out of support and will not receive security updates in the future. Please refer to https://aka.ms/dotnet-core-support for more information about the support policy. [/Users/username/sources/AvalonStudio/AvalonStudio/Avalonia.Designer.HostApp/Avalonia.Designer.HostApp.csproj]
/usr/local/share/dotnet/sdk/5.0.103/NuGet.targets(131,5): error : Unable to load the service index for source https://dotnet.myget.org/F/dotnet-core/api/v3/index.json. [/Users/username/sources/AvalonStudio/AvalonStudio/AvalonStudio/AvalonStudio.csproj]
/usr/local/share/dotnet/sdk/5.0.103/NuGet.targets(131,5): error :   The SSL connection could not be established, see inner exception. [/Users/username/sources/AvalonStudio/AvalonStudio/AvalonStudio/AvalonStudio.csproj]
/usr/local/share/dotnet/sdk/5.0.103/NuGet.targets(131,5): error :   The remote certificate is invalid according to the validation procedure: RemoteCertificateNameMismatch [/Users/username/sources/AvalonStudio/AvalonStudio/AvalonStudio/AvalonStudio.csproj]

Build FAILED.
```

I'm not sure how to bypass the certificate issues within `dotnet restore`, but accessing https://dotnet.myget.org/F/dotnet-core/api/v3/index.json via Firefox (bypassing the issue) gives 404 error.

**Comment by najlot** [comment]
@qezz i'm sorry if the answer is too late

The url https://dotnet.myget.org/F/dotnet-core/api/v3/index.json does not exist.
The url dotnet.myget.org redirects to dotnet.microsoft.com.
Where have you got "dotnet.myget.org" from?

There is the content of the current (and working) nuget.config:
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <clear/>
    <add key="nuget.org" value="https://www.nuget.org/api/v2/" />
    <add key="avalonia-all" value="https://nuget.avaloniaui.net/repository/avalonia-all/" />
    <add key="XamlBehaviors" value="https://www.myget.org/F/xamlbehaviors-nightly/api/v2" />
    <add key="sharpgen" value="https://www.myget.org/F/sharpgentools/api/v3/index.json" />
    <add key="cli-deps" value="https://dotnetfeed.blob.core.windows.net/dotnet-core/index.json" />
    <add key="DockNightly" value="https://www.myget.org/F/dock-nightly/api/v2" />
  </packageSources>
</configuration>

**Comment by qezz** [comment]
Hi @najlot! 

At time, I haven't changed anything in the environment, just was following the build guide as following

```
git clone https://github.com/VitalElement/AvalonStudio --recursive
cd AvalonStudio/AvalonStudio/AvalonStudio
dotnet restore
dotnet build
```

**Comment by najlot** [comment]
I have cloned my fork just now and it builds just fine...

![image](https://user-images.githubusercontent.com/38798099/121818192-fcdd2480-cc85-11eb-891a-d6f75249e377.png)

Which branch are you using?

**Comment by najlot** [comment]
And it runs with "dotnet run -f net5.0"

![image](https://user-images.githubusercontent.com/38798099/121818280-737a2200-cc86-11eb-8839-449429b8de46.png)

I have no idea about mac... could it be something like a global nuget.config?

**Comment by qezz** [comment]
Hey. I cannot reproduce the issue anymore, so I'm closing it. Thank you!
